hq_stage/urls.py
from django.conf.urls import url

from . import views


app_name = 'hq_stage'
urlpatterns = [
      url( r'^batch/(?P<pk>\d+)/'
         , views.BatchView.as_view()
         , name='batch'
         )
    , url( r'^batch/$'
         , views.BatchListView.as_view()
         , name='batch_list'
         )
    , url( r'^currency/(?P<pk>\d+)/'
         , views.CurrencyUpdateView.as_view()
         , name='currency'
         )
    , url( r'^currency/$'
         , views.CurrencyListView.as_view()
         , name='currency_list'
         )
    , url( r'^exchange/(?P<pk>\d+)/'
         , views.ExchangeUpdateView.as_view()
         , name='exchange'
         )
    , url( r'^exchange/$'
         , views.ExchangeListView.as_view()
         , name='exchange_list'
         )
    , url( r'^offer/(?P<pk>\d+)/'
         , views.OfferUpdateView.as_view()
         , name='offer'
         )
    , url( r'^offer/$'
         , views.OfferListView.as_view()
         , name='offer_list'
         )
    , url( r'^upload-api/$'
         , views.UploadView.as_view()
         , name='api'
         )
    , url( r''
         , views.DocView.as_view()
         , name='doc'
         )
]

hq_stage/templates/hq_stage/batch.html
{% extends "hq_main/hq.html" %}

{% block title %}
batch {{ batch.id }} - {{ batch.date_created|date:'l, F jS o - g:iA' }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<div>Batch ID: {{ batch.id }}</div>
<div>Date Created {{ batch.date_created|date:'l, F jS o - g:iA' }}</div>
<div>Processed:
  {% if batch.processed %}
    Yes
  {% else %}
    No
  {% endif %}
</div>
{% endblock %}

hq_stage/templates/hq_stage/currency_update.html
{% extends "hq_main/hq.html" %}

{% block title %}
update {{ currency.currency_name }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<p>Currency ID: {{ currency.id }}</p>
<p>Insert Date: {{ currency.insert_date }}</p>
<p>Fields in Error:</p>
<div>
  {{ currency.fields_in_error }}
</div>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <p>Submit button not provided, sorry.</p>
</form>
{% endblock %}

hq_stage/templates/hq_stage/doc.html
{% extends "hq_main/hq.html" %}

{% block title %}
HQ Warehouse Staging Area
{% endblock %}

{% block page_body %}
{{ block.super }}

<h1>HQ Warehouse Staging Area</h1>

<h3>Available commands</h3>

<pre>
hqs-load-table [-h] [-b &lt;batch&gt;] -f &lt;csv_file&gt; -t &lt;table&gt;

  -h  Print usage.
  -b  Batch number to use, if such a batch does not exist yet or has
      already been processed this argument will be ignored.
  -t  The table to load data into, either `currency`, `exchange-rate` or
      `offer`.
  -f  CSV file with relevant data for the table specified with -t.
</pre>

<pre>
hqs-print-errors [-h] -t &lt;table&gt;

  -h  Print usage.
  -t  Check the table for rows that are in error (and the error has not
      been set to ignored), either `currency`, `exchange-rate` or `offer`.
</pre>

<div>Available Tables</div>

<ul>
  <li><code>currency</code></li>
  <li><code>exchange-rate</code></li>
  <li><code>offer</code></li>
</ul>

<h3>API</h3>

<p>
  <code>POST</code> into <code>{% url 'hq_stage:api' %}</code>
</p>

<p>Example</p>

<pre>
POST {% url 'hq_stage:api' %} HTTP/1.1

{ 'batch' : 3  // batch is optional
, 'object_type' : 'currency'
, 'object_data' :
    { 'external_id' : '3'
    , 'currency_code' : 'GBP'
    , 'currency_name' : 'British Pound'
    }
}
</pre>
{% endblock %}

hq_stage/templates/hq_stage/exchange_update.html
{% extends "hq_main/hq.html" %}

{% block title %}
update {{ exchange.date_valid }} - {{ exchange.currency_rate }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<p>Exchange rate ID: {{ exchange.id }}</p>
<p>Insert Date: {{ exchange.insert_date }}</p>
<p>Fields in Error:</p>
<div>
  {{ exchange.fields_in_error }}
</div>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <p>Submit button not provided, sorry.</p>
</form>
{% endblock %}

hq_stage/templates/hq_stage/offer_update.html
{% extends "hq_main/hq.html" %}

{% block title %}
update {{ offer.source_system_code }} - {{ offer.hotel_id }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<p>Offer ID: {{ offer.id }}</p>
<p>Insert Date: {{ offer.insert_date }}</p>
<p>Fields in Error:</p>
<div>
  {{ offer.fields_in_error }}
</div>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <p>Submit button not provided, sorry.</p>
</form>
{% endblock %}